# This file is based off of the post: https://medium.com/mobileforgood/9cedb8348a62


sudo: required
services:
- docker
language: minimal

# Only run travis on master
branches:
  only:
  - master

env:
  global:
  - REGISTRY_USER=amcolash
  # REGISTRY_PASS is the secure variable below
  - secure: AcZxPkjT1H96CGLqtY5APx5NLFQXt3q88cJ6768/A1YhH4HrzfvxuymEzEkK8dr1xLKYOBOz/wF1kVWVs1SA9igLn/jUDZVeqtyGqBHu+92VH1ik/D0kIZSdWdTk3SzWIloqO1NwPl84typIblPrScB30e0Yj0xt3/UAx09XWWSHHmc0S6ZLvuOaP7u62QfM/qKtIx9Whc/gq+w6z9TCNAFA1MG/xU6B50ZAtwl7zSe/S4NNMIeQUtiXsy37bJnO0+gD1W2IyLN4NzohQzi1AaJGwE7dZ1fqdLbjUt1cOTvjuKQxi81wt/vb9ytAcLVCLz6zQW5qDdfRSgtInfIfkf+x5CXNrkzEs86QHnfJZMF1ueNhb9M1l4uIiZywOBFKCpUl45FBpdHttD8GtiZSD797Y6S0h15VuTYDcnauGwvvf8zYcBD1bfBqaXcsnIuHD8w7m6yE6Ew3PGRbXvj4/SBInoJ6TkIKZitxCj1pulc2CXFdgeNdAOK4JUYg0ew8K2iv/3rCFrUtoyinhE5y7BIkvTTdndciZ0H9/BLpXswYvVFQ8VceSIyoKZQ8O4BriabYxjFGTp/8cYbdXNlCGfJWbFtGPQo4+Lj6zfG0q22Wa2BUvOYdmhv/xPRpUK1jYFC9MRkwoZmxg2pXXuO9l6bxApKiP7Vo+yDFQjUtOos=
  # UPGRADE_SERVER is the secure variable below
  - secure: fpwMXFRwEb7VIyOHMTjCB2hCEtoLDTuz8HLtM0TikJ3BSYCYClJcF7X4Y5aT60EJpwA9ZIFs12pnTofOsWpilAFGUSAfeNgkEOytDXDHVUZJC7gDte0KXmVqffSPUSPdk9jRY9C02SW4Z5qTKa6XkEqA0huZbCxMP+OFAix6YMTs6USWSIvSBmonA3V5n+haS+PAfUum2OJ7HmKNbGYMK2/4FIAi1gWamLWLTyqHzlkgDKmlYyFhl0KRSRVh0hKy6eyWXID7KbgXhFgGYxhBk0/oMlHioO6HZMJ0UHVyIYOUnwfHY2C6RJhiD+ZiWh+SOP+Gqhdym2lgCEL8PlxobwKIxwe9DoU4wZB6IIIEEwI5rPjgT/FQDqPFP1zcvvMtfmY2ncugbNOjcgCxm8CF+U4aAgEFbi4/C35l9WFCqMxYuxQC3m5ZojyqP+LHgJUZTitSBaZyKElmIrraKh4TU80vwkf0IfPShq/jFCN++wPdbIShrgpVuvEo/MEeoZnUcJFtd6axrXRKyEqGhi4cZeRaA6rzwTdYCsmTD0mnM7W5OHgZTlqHS1HU7Qn/DtI6wcx35omx+Q0g0nynxTDmhTf9ddPcFP0x470RVcTj3jw9HiOGuNmpJufvRerz+F52JlqHcZfwyjl4SHp810pHOUsIHqKsF1LjRdKblh7qob8=

before_script:
- docker pull amcolash/transmission-yify || true

script:
- docker build --pull --cache-from amcolash/transmission-yify --tag amcolash/transmission-yify
  .
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push amcolash/transmission-yify
  on:
    branch: master

after_script:
  # List docker images after the build
  - docker images
  # Send upgrade command to current (and then add newline to output for travis)
  - curl --insecure --max-time 15 -X POST $UPGRADE_SERVER; echo
  # Update the README file on docker hub
  - |
    docker run \
    -v ${PWD}/README.md:/data/README.md \
    -e DOCKERHUB_USERNAME="$REGISTRY_USER" \
    -e DOCKERHUB_PASSWORD="$REGISTRY_PASS" \
    -e DOCKERHUB_REPO_PREFIX=amcolash \
    -e DOCKERHUB_REPO_NAME=transmission-yify \
    sheogorath/readme-to-dockerhub
