sudo: required
services:
- docker
language: minimal
branches:
  only:
  - master
env:
  global:
  - REGISTRY_USER=amcolash
  - secure: lDpP170LXN8lSgzhlpgYFs0bGNEYT8pQZ0u4Xa7FGGP8VDY60CSui5sc+8D6586CeCoJlHZqfV9WxoQHCp77Ie+452WGp+4Zmp5/6xWwKeHLxNzbSW97E2VjrsebvaVqU+lkTLHSzc+K54Yfubw+s/w4xtwiJulK4k2k/N2+OOrdyEGW778USBUXteXOrNMU9cRIf2Y5z26pLyC34CHny7itsHGgVtCyk73gb2eSHUH1poRXgRIgh+nDxKfMFD/5vfZDyNhEDHUGxRUnh/ariHH731jgNaMJStld0SuqsCtcVycoJ1Zx7A0VVgpEhrTt4wXp6SsbM9HJV/SuMhoCTG9sxjnh/vkpqTfmef842fDp5oX53GkqQ8S1SQtTCDWK20NtPOME2hXwI1uPmtI886hQ+z/SvY0IAWouWXwkXaT6qL6vEsjZpJXCbTmZJQ1KPUF8kAPJhfA5vcPhOlpHPQf7AH1qYmmnbJJpF2URiAIcfXWIjzTTqo3OfMFIuEzuFwZD+Y7n5wS0Xowe1ti3iTZEGqsgqolRQNzw9WLmU5qtMg+g4t5qsSn+iyjhZtZf4WxUSgDU7PpSQ2FlTVGqR7zyJsiBqoSaPuq2F8VSWj17TStFpKU/YbekAeeJvePsjFyM/kiQxlUlLFgVrIxXnHrkUlOzvzClCHEl1AFoMw8=
before_script:
- docker pull amcolash/transmission-yify || true
script:
- docker build --pull --cache-from amcolash/transmission-yify --tag amcolash/transmission-yify
  .
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push amcolash/transmission-yify
  on:
    branch: master
after_script:
- docker images
- curl --max-time 15 -X POST $UPGRADE_SERVER; echo
- |-
  docker run \
  -v ${PWD}/README.md:/data/README.md \
  -e DOCKERHUB_USERNAME="$REGISTRY_USER" \
  -e DOCKERHUB_PASSWORD="$REGISTRY_PASS" \
  -e DOCKERHUB_REPO_PREFIX=amcolash \
  -e DOCKERHUB_REPO_NAME=transmission-yify \
  sheogorath/readme-to-dockerhub
