version: '3.2'
services:
  # vpn was moved out from docker to host OS recently

  transmission:
    image: dperson/transmission
    container_name: transmission
    environment:
      - TR_DOWNLOAD_QUEUE_SIZE=30
      - TR_PEER_PORT_RANDOM_ON_START=true
      - TR_MAX_PEERS_GLOBAL=800
      - TR_PEER_LIMIT_GLOBAL=800
      - TR_PEER_LIMIT_PER_TORRENT=200
      - TR_INCOMPLETE_DIR_ENABLED=true
      - TR_DOWNLOAD_DIR=/var/lib/transmission-daemon/completed
      - TR_RATIO_LIMIT_ENABLED=false
    networks:
      - app_network
    ports:
      - 9091:9091
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}:/var/lib/transmission-daemon
      - ${TV_DIR}:/TV
      - ./scripts/start.sh:/scripts/start.sh:ro
    env_file:
      - .env
    entrypoint: ['/sbin/tini', '--']
    command: ['/scripts/start.sh']

  server:
    image: amcolash/transmission-yify
    build: ./
    container_name: server
    restart: unless-stopped
    depends_on:
      - transmission
    links:
      - transmission:transmission
    networks:
      - app_network
    ports:
      - 9090:9090
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}:/data
      - ${TV_DIR}:/TV
      - .ssh:/root/.ssh
      - .cert:/usr/src/app/.cert
    env_file:
      - .env

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
