version: '2'
services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}:/data
      - ./get_ip.sh:/scripts/transmission-post-start.sh:ro
    env_file:
      - .env
    environment:
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.0.0/24

  proxy:
    image: haugene/transmission-openvpn-proxy
    container_name: proxy
    restart: always
    links:
      - transmission
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro

  client:
    image: amcolash/transmission-yify
    container_name: client
    restart: always
    links:
      - transmission
    ports:
      - 9000:9000
    volumes:
      - ${DATA_DIR}:/data
    env_file:
      - .env