version: '2'
services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}:/data
      - ${TV_DIR}:/TV
      - ${VIDEO_DIR}:/Videos
      - ./get_ip.sh:/scripts/transmission-post-start.sh:ro
    env_file:
      - .env
    environment:
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.0.0/24
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=15

  client:
    image: amcolash/transmission-yify
    build: ./
    container_name: client
    restart: unless-stopped
    links:
      - transmission
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}:/data
    env_file:
      - .env

  ouroboros:
    image: circa10a/ouroboros
    container_name: ouroboros
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: --monitor transmission client
